services:
  backend:
    build:
      context: .
      dockerfile: ./docker/fastify/Dockerfile
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    ports:
      - "4000:3000"
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: fastify
      MYSQL_PASSWORD: password
      MYSQL_USER: fastify
    ports:
      - "3936:3000"
    volumes:
      - fastify_db_data:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

volumes:
  backend_node_modules:
  fastify_db_data: