services:
  backend:
    build:
      context: .
      dockerfile: ./docker/fastify/Dockerfile
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    ports:
      - "4000:3000"
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: ./docker/angular/Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    tty: true
    command: sh -c "ng serve --host=0.0.0.0"
    depends_on:
      - backend

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: fastify
      MYSQL_PASSWORD: password
      MYSQL_USER: fastify
    ports:
      - "3936:3306"
    volumes:
      - fastify_db_data:/var/lib/mysql

volumes:
  backend_node_modules:
  frontend_node_modules:
  fastify_db_data: